import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const renderer = readFileSync(join(root, 'src/injected.js'), 'utf8');
const css = readFileSync(join(root, 'assets/ui-quota/design.css'), 'utf8');
const launcher = readFileSync(join(root, 'bin/codex-header'), 'utf8');
const mount = renderer.match(/function mountCapsule\(\) \{([\s\S]*?)\n  function suppressLegacyInstances/);
const widthMeasure = renderer.match(/function measureAvailableWidth\(element\) \{([\s\S]*?)\n  function renderHost/);
const updateMode = renderer.match(/function updateMode\(\) \{([\s\S]*?)\n  function ensureHostHitArea/);
const resizeBinding = renderer.match(/function bindResizeObserver\(\) \{([\s\S]*?)\n  \/\/ __MOUNT_POINT_LOGIC_BEGIN__/);

assert.ok(mount, 'mountCapsule implementation must remain present');
assert.ok(widthMeasure, 'available-width measurement must remain present');
assert.ok(updateMode, 'responsive mode update must remain present');
assert.ok(resizeBinding, 'layout observer must remain present');
assert.match(mount[1], /if \(changed\) \{\s*renderHost\(\)/, 'healthy periodic mount checks must not rewrite the capsule DOM');
assert.match(mount[1], /周期性挂载巡检[\s\S]*?updateMode\(\);/, 'unchanged mounts must refresh geometry when position changes without resize');
assert.doesNotMatch(widthMeasure[1], /currentHostWidth|maxCanExpand|freeSpaceToRight/, 'mode measurement must not use the capsule width as available space');
assert.match(widthMeasure[1], /firstVisibleLayoutRect\(element\.nextElementSibling\)/, 'display:contents anchors must resolve to a visible native child');
assert.match(widthMeasure[1], /rightControl\.contains\(element\)/, 'right boundary must exclude flex rows containing the injected capsule');
assert.doesNotMatch(renderer, /host\.shadowRoot\.innerHTML\s*=\s*style/, 'host rerenders must preserve the capsule root');
assert.match(updateMode[1], /if \(popover\?\.classList\.contains\('is-visible'\)\) positionPopover\(\)/, 'visible popover follows layout changes even when the mode is unchanged');
assert.doesNotMatch(resizeBinding[1], /observe\(host\?\.parentElement\)|observe\(toolbar\)/, 'resize observer must not subscribe to the host flex container');
assert.match(resizeBinding[1], /observe\(host\.nextElementSibling\)/, 'right-side native anchor changes must be observed');
assert.match(renderer, /previousFocusIndex[\s\S]*focus\(\{ preventScroll: true \}\)/, 'popover rerenders restore keyboard focus and scrolling');
assert.match(renderer, /let pointerMoveFrame = 0[\s\S]*requestAnimationFrame\(/, 'document-level pointer fallback is frame-batched');
assert.match(renderer, /on\(document, 'pointermove', handleDocumentPointerMove, true\)/);
assert.doesNotMatch(renderer, /on\(document, 'mousemove'/, 'do not process duplicate mouse and pointer streams');
assert.match(renderer, /if \(document\.hidden\) \{[\s\S]*?if \(countdownTimer\) clearInterval\(countdownTimer\)[\s\S]*?if \(healthTimer\) clearInterval\(healthTimer\)/, 'renderer countdowns and mount repair stop while Codex is hidden');
assert.match(renderer, /function isDarkAppearance\(\)/);
assert.match(renderer, /rootThemeObserver\.observe\(document\.documentElement, \{ attributes: true/);
assert.match(renderer, /on\(systemTheme, 'change'/, 'OS appearance changes update the widget unless the app explicitly pins a theme');
assert.match(renderer, /mini-pie-empty/);
assert.match(css, /container-type:inline-size;container-name:quota-card/);
assert.match(css, /@container quota-card \(max-width: 719px\)/);
assert.match(css, /@container quota-card \(max-width: 520px\)/);
assert.match(launcher, /\$HOME\/plugins\/codex-usage-header/);
assert.match(launcher, /\$HOME\/\.codex\/plugins\/codex-usage-header/);

console.log('✓ Reduced redundant UI work and responsive compatibility contracts passed');
