import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

console.log('Testing: renderer interaction and mounting contract...');

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const source = readFileSync(join(rootDir, 'src', 'injected.js'), 'utf8');

assert.match(source, /pointer-events:auto!important/);
assert.match(source, /-webkit-app-region:no-drag/);
assert.match(source, /codex-usage-header-host/);
assert.match(source, /function renderAll/);
assert.match(source, /class="capsule-toggle"/);
assert.match(source, /class="capsule-separator"/);
assert.match(source, /querySelector\('\.capsule'\)/);
assert.match(source, /classList\.toggle\('is-expanded', expanded\)/);
assert.match(source, /togglePopoverFromCapsule\(\)/);
assert.match(source, /contains\('details-trigger'\) \|\| node\?\.classList\?\.contains\('capsule-toggle'\)/);
assert.match(source, /attachShadow\(\{ mode: 'open' \}\)/);
assert.match(source, /__codexUsageHeaderCommand__/);
assert.match(source, /__codexUsageHeaderSetUsage__/);
assert.match(source, /__codexUsageHeaderSetRefreshError__/);
assert.match(source, /pointerover/);
assert.match(source, /pointerleave/);
assert.match(source, /addEventListener\('click'/);
assert.match(source, /popover.*body|body.*popover/s);
assert.match(source, /position:fixed;z-index:2147483646/);
assert.match(source, /@keyframes quota-refresh-spin/);
assert.match(source, /align-items:center;gap:5px/);
assert.match(source, /\.track\{flex:none;width:70px;height:12px/);
assert.match(source, /grid-template-columns:52px 122px/);
assert.match(source, /meta-actions\{display:flex;align-items:center;justify-content:space-between;gap:18px;width:100%;white-space:nowrap;flex-wrap:nowrap/);
assert.match(source, /\.divider\{flex:none;width:1px;height:16px;margin:0/);
assert.match(source, /card-refresh/);
assert.match(source, /refreshIntervalSeconds/);
assert.match(source, /credits-copy/);
assert.match(source, /mini-pie/);
assert.match(source, /rateLimitsByLimitId/);
assert.match(source, /secondary\.remainingPercent === 0/);
assert.match(source, /usedPercent: 100, remainingPercent: 0/);
assert.match(source, /function isWeeklyExhausted/);
assert.match(source, /weeklyExhausted \? '' :/);
assert.match(source, /weeklyResetSuffix/);
assert.match(source, /formatDate\(window\.resetsAt, true\)/);
assert.match(source, /creditBalance/);
assert.match(source, /'<span class="balance">' \+ esc\(t\('balance'\) \+ '：' \+ usageState\.creditBalance\.displayValue\) \+ '<\/span>'/);
assert.doesNotMatch(source, /designIcon\('info'\)/);
assert.match(source, /function formatCreditBalance/);
assert.match(source, /numeric\.toFixed\(2\)/);
assert.match(source, /中 \/ EN/);
assert.match(source, /showFiveHours/);
assert.match(source, /planType/);
assert.match(source, /用量额度/);
assert.match(source, /合理AI协作/);
assert.match(source, /完全重置（每周 \+ 5 小时）/);
assert.match(source, /credit-icon/);
assert.match(source, /resetCredit/);
assert.match(source, /切换底部面板显示/);
assert.match(source, /显示\\\/隐藏侧边面板/);
assert.match(source, /placement: isNewChat \? 'new-chat' : 'thread'/);
assert.match(source, /data-app-shell-header-toolbar="true"/);
assert.match(source, /data-app-shell-header-obstacle="true"/);
assert.match(source, /rect\.top < 80 && rect\.bottom > 0/);
assert.match(source, /placement: 'chat'/);
assert.match(source, /referenceRect\.left - toolbarRect\.left - titleNeed - 12/);
assert.match(source, /available < 64/);
assert.match(source, /if \(!records\.some\(isHeaderMutation\)\) return/);
assert.match(source, /getMountPoint: \(\) =>/);
assert.match(source, /existing\.dataset\.placement = point\.placement/);
assert.match(source, /__codexUsageHeaderSetExtendedUsage__/);
assert.match(source, /quota-extension/);
assert.match(source, /quota-extension-section/);
assert.match(source, /quota-extension-range-tab/);
assert.match(source, /quota-extension-token-table/);
assert.match(source, /quota-extension-model-button/);
assert.match(source, /aria-haspopup="listbox"/);
assert.match(source, /quota-extension-model-option/);
assert.match(source, /selectedTokenModel/);
assert.match(source, /model: '模型'/);
assert.match(source, /allModels: '汇总'/);
assert.match(source, /hasTokenModelUsage/);
assert.match(source, /const summaryItems = rangeData\.summaryItems \|\| rawItems/);
assert.match(source, /tokenDonutStops\(rangeData\)/);
assert.match(source, /quota-dashboard/);
assert.match(source, /header-module-toggle/);
assert.match(source, /moduleButton\('reset', 'coupon'/);
assert.match(source, /moduleButton\('google', 'sparkle'/);
assert.match(source, /moduleButton\('tokens', 'tokenChart'/);
assert.match(source, /otherModelsTotal/);
assert.match(source, /renderExtendedUsage/);
assert.match(source, /Gemini AI Pro/);
assert.match(source, /Token使用量/);
assert.match(source, /Token处理量/);
assert.match(source, /header-module-toggle/);
assert.match(source, /data-module/);
assert.match(source, /aria-pressed/);
assert.match(source, /account-mask-toggle-btn/);
assert.match(source, /extendedUsageState\.antigravity\.userSelectedAccount = account/);
assert.doesNotMatch(source, /emitCommand\('promote-account'/);
assert.match(source, /maskButton\s*\+\s*rebalanceButtonHtml\s*\+\s*'<\/div>'/);
assert.match(source, /const rebalanceButtonHtml = accounts\.length > 1 && enableDynamic/);
assert.match(source, /statusForAccess = isZh \? '使用中' : 'In Use'/);
assert.match(source, /const isSelected = \(acc\.email === activeAccount\.email\)/);
assert.match(source, /const isInUse = info\?\.status === 'COOLING'/);
assert.match(source, /tabLabel = '<span class="quota-tab-dot" aria-hidden="true"><\/span>' \+ tabLabel/);
assert.match(source, /'备' \+ fallbackIndex/);
assert.match(source, /aria-label="' \+ esc\(accountDescription\)/);
assert.match(source, /aria-label="' \+ esc\(rebalanceDescription\)/);
assert.match(source, /maskAccountNames/);
assert.match(source, /function maskAccountName/);
assert.match(source, /document\.documentElement\?\.lang/);
assert.match(source, /voucher-loading-spinner/);
assert.match(source, /loadingVouchers/);
assert.match(source, /isVoucherLoading/);
assert.match(source, /failover-toggle-btn/);
assert.match(source, /renderFailoverToggleButton/);
assert.match(source, /failover-tooltip/);
assert.match(source, /toggleFailoverMode/);
assert.doesNotMatch(source, /__codexUsageBridgeUrl__/);
assert.doesNotMatch(source, /refresh-interval/);
assert.doesNotMatch(source, /iconMarkup\('database'\)/);
assert.doesNotMatch(source, /credits-trigger|showUsageModal|formatUpdatedAt|更新于刚刚/);
assert.doesNotMatch(source, /role="dialog"/);
assert.doesNotMatch(source, /\.refresh-btn/);
assert.match(source, /quota-rebalance-tooltip" role="tooltip"/);
assert.doesNotMatch(source, /quota-rebalance-tooltip\{position:absolute;bottom:100%/);
assert.doesNotMatch(source, /primary-countdown\{min-width:128px/);
assert.doesNotMatch(source, /本机处理量 · 非账单用量/);

console.log('✓ Renderer interaction and mounting contract passed!');
