import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

console.log('Testing: renderer interaction and mounting contract...');

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const source = readFileSync(join(rootDir, 'src', 'injected.js'), 'utf8');

assert.match(source, /pointer-events:auto!important/);
assert.match(source, /-webkit-app-region:no-drag/);
assert.match(source, /codex-usage-header-host/);
assert.match(source, /function renderAll/);
assert.match(source, /attachShadow\(\{ mode: 'open' \}\)/);
assert.match(source, /__codexUsageHeaderCommand__/);
assert.match(source, /__codexUsageHeaderSetUsage__/);
assert.match(source, /__codexUsageHeaderSetRefreshError__/);
assert.match(source, /pointerover/);
assert.match(source, /pointerleave/);
assert.match(source, /addEventListener\('click'/);
assert.match(source, /popover.*body|body.*popover/s);
assert.match(source, /position:fixed;z-index:2147483646/);
assert.match(source, /@keyframes quota-refresh-spin/);
assert.match(source, /align-items:center;gap:5px/);
assert.match(source, /\.track\{flex:none;width:70px;height:12px/);
assert.match(source, /grid-template-columns:52px 122px/);
assert.match(source, /meta-actions\{display:flex;align-items:center;justify-content:space-between;gap:18px;width:100%;white-space:nowrap;flex-wrap:nowrap/);
assert.match(source, /\.divider\{flex:none;width:1px;height:16px;margin:0/);
assert.match(source, /card-refresh/);
assert.match(source, /refreshIntervalSeconds/);
assert.match(source, /credits-copy/);
assert.match(source, /mini-pie/);
assert.match(source, /rateLimitsByLimitId/);
assert.match(source, /secondary\.remainingPercent === 0/);
assert.match(source, /usedPercent: 100, remainingPercent: 0/);
assert.match(source, /function isWeeklyExhausted/);
assert.match(source, /weeklyExhausted \? '' :/);
assert.match(source, /weeklyResetSuffix/);
assert.match(source, /formatDate\(window\.resetsAt, true\)/);
assert.match(source, /creditBalance/);
assert.match(source, /function formatCreditBalance/);
assert.match(source, /numeric\.toFixed\(2\)/);
assert.match(source, /中 \/ EN/);
assert.match(source, /showFiveHours/);
assert.match(source, /planType/);
assert.match(source, /用量额度/);
assert.match(source, /合理AI协作/);
assert.match(source, /完全重置（每周 \+ 5 小时）/);
assert.match(source, /credit-icon/);
assert.match(source, /resetCredit/);
assert.match(source, /切换底部面板显示/);
assert.match(source, /显示\\\/隐藏侧边面板/);
assert.match(source, /placement = threadAction \? 'thread' : 'new-chat'/);
assert.match(source, /existing\.dataset\.placement = point\.placement/);
assert.match(source, /__codexUsageHeaderSetExtendedUsage__/);
assert.match(source, /quota-extension/);
assert.match(source, /quota-extension-section/);
assert.match(source, /quota-extension-range-tab/);
assert.match(source, /quota-extension-token-table/);
assert.match(source, /renderExtendedUsage/);
assert.match(source, /Gemini AI Pro/);
assert.match(source, /Token使用量/);
assert.match(source, /Token处理量/);
assert.match(source, /voucher-toggle-btn/);
assert.match(source, /stats-toggle-btn/);
assert.doesNotMatch(source, /__codexUsageBridgeUrl__/);
assert.doesNotMatch(source, /refresh-interval/);
assert.doesNotMatch(source, /iconMarkup\('database'\)/);
assert.doesNotMatch(source, /credits-trigger|showUsageModal|formatUpdatedAt|更新于刚刚/);
assert.doesNotMatch(source, /role="dialog"/);
assert.doesNotMatch(source, /\.refresh-btn/);
assert.doesNotMatch(source, /role="tooltip"/);
assert.doesNotMatch(source, /primary-countdown\{min-width:128px/);

console.log('✓ Renderer interaction and mounting contract passed!');
